updated config and docksal after composer update

diff --git a/.docksal/commands/css-compile b/.docksal/commands/css-compile
--- a/.docksal/commands/css-compile
+++ b/.docksal/commands/css-compile
@@ -2,7 +2,8 @@
 
 ## Run npm in the theme folder to Compile CSS.
 ##
-## Usage: fin compile-css
+## Usage: fin css-compile
+##                   --clean reinstalls dependencies (optional)
 ##
 
 source ${DOCKSAL_PATH}/.docksal/helpers
@@ -13,6 +14,23 @@ check_override $@
 cd ${THEME_PATH}
 
 # Install npm
-fin npm install
-fin exec ./node_modules/.bin/gulp styles
+fin exec nvm install
+# Set theme nodeJS version as default.
+fin exec nvm alias default $(cat ./.nvmrc)
+fin exec nvm use
+
+if [[ ! -d "node_modules" || $1 == "--clean" ]]; then
+  echo-yellow "Installing dependencies…"
+  fin exec npm ci
+fi
+if [ -d "node_modules" ]; then
+  echo-green "All set up; ready to compile!"
+fi
+
+fin exec npm run build:css
+
+# Provide useful message if fails
+if [ $? -eq 1 ]; then
+  echo-red "Check theme package.json & see https://knowledge.annertech.com/coding/build-tools/"
+fi
 fin cr
